# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b52e0696771ff2f54f14c334bde5fcc5244dd33fcaedfe6930e3d104b1a4fd42615672dd45e94eccad983db9f835591efc41c1ee97f7c417715eb20821904a

test:
  secret_key_base: 12b14ba7f488cc7d0e896c695d361bb91f76a6f099739131364c28978b846a13fd62dbe42f820c94e7db360ed4dc1b7b811c3aeb344e9b868bd7aca6888b9fd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
